#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate the harmony_text TC stream-v2 fixtures by cloning the harmony
(token-id) fixtures and re-recording only the Dynamo per-chunk emit through the
TEXT path.

Why this exists
---------------
The `harmony` (token-id) and `harmony_text` rows drive the SAME
HarmonyToolStreamParser through two entry points:
  - harmony      -> parse_tool_call_streaming_incremental(delta_token_ids)
  - harmony_text -> parse_tool_call_streaming_text(delta_text)

The token-id row had the full 31-case scenario grid; the text row had only 7
hand-authored cases that used different sub-case ids. So in the conformance
table the two rows shared only 4 of 31 columns, and the text path's per-chunk
streaming emit was barely tested — even though the text path is the realistic
path for engines that stream decoded text (vLLM/SGLang) and the only path used
for batch-on-stream.

This clones every harmony token case into harmony_text verbatim — same chunks,
same vLLM/SGLang per-chunk `expected` and `normal_text` (those are recorded
against these exact chunk boundaries, so they stay valid) — swapping ONLY
`expected.dynamo_v2` / `normal_text.dynamo_v2` for the text-path recording from
`record_dynamo_stream --text`. The result: the two rows cover an identical
scenario grid through both parser paths, the table columns align, and the text
path's per-chunk emit is regression-locked. The prior hand-authored text cases
(whole-payload, boundary-split, length-truncation) are subsumed: the parser
ignores the finish_reason *value* (the harness only uses it to decide when to
call finish()), and the token grid already covers finer chunking plus the
truncation/unterminated-JSON scenarios.

Usage
-----
  python3 conformance/utils/gen_harmony_text_fixtures.py
"""
import json
import os
import subprocess
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)
from build_stream_fixtures import _delta_flow, _indent, _q  # noqa: E402  (reuse the writer's helpers)

REPO_ROOT = os.path.dirname(os.path.dirname(HERE))  # frontend-crates/
TOKEN_DIR = os.path.join(
    REPO_ROOT, "conformance/toolcalling/fixtures-stream-v2/harmony"
)
TEXT_DIR = os.path.join(
    REPO_ROOT, "conformance/toolcalling/fixtures-stream-v2/harmony_text"
)
# Peer impls carried verbatim from the token fixture (their per-chunk data is
# tied to these exact chunk boundaries). dynamo_v2 is re-recorded via the text path.
PEER_IMPLS = ("vllm_python", "sglang_python")
MODEL_LABEL = "gpt-oss (harmony, text)"

HEADER = [
    "# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.",
    "# SPDX-License-Identifier: Apache-2.0",
    "",
    "# Streaming fixture (per-chunk, per-impl). Each chunk: input (delta_text +",
    "# optional delta_token_ids) and `expected.<impl>` = tool-call deltas emitted at",
    "# that chunk. `normal_text.<impl>` (when non-empty) = non-tool text (leaks show",
    "# here). Assembled result is derived by concatenating per index. A delta:",
    "# {index, id?, name?, arguments?}; id:true = an id was emitted.",
    "#",
    "# Generated by gen_harmony_text_fixtures.py: clone of the harmony (token-id)",
    "# fixtures with expected.dynamo re-recorded through the text path. Do not edit",
    "# by hand; rerun the generator instead.",
]


def record_text_path(token_file):
    """Run record_dynamo_stream --text over a token fixture; return
    {case_id: [{deltas, normal_text}, ...]} (one entry per source chunk, with the
    finish() emit merged into the last chunk)."""
    out = subprocess.run(
        [
            "cargo",
            "run",
            "--quiet",
            "-p",
            "dynamo-parsers-v2",
            "--bin",
            "record_dynamo_stream",
            "--",
            token_file,
            "--text",
        ],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if out.returncode != 0:
        raise RuntimeError(f"record_dynamo_stream failed on {token_file}:\n{out.stderr[-2000:]}")
    return json.loads(out.stdout)


def emit_case(lines, cid, case, text_rec):
    lines.append(f"  {cid}:")
    if "description" in case:
        lines.append(f"    description: {_q(case['description'])}")
    if "ref" in case:
        lines.append(f"    ref: {_q(case['ref'])}")
    if case.get("tools"):
        lines.append("    tools:")
        lines.append(
            _indent(
                yaml.safe_dump(
                    case["tools"], default_flow_style=False, allow_unicode=True, sort_keys=False
                ).rstrip(),
                4,
            )
        )
    lines.append("    chunks:")
    chunks = case.get("chunks", [])
    for ci, chunk in enumerate(chunks):
        lines.append(f"    - delta_text: {_q(chunk.get('delta_text', ''))}")
        if "delta_token_ids" in chunk:
            ids = ", ".join(str(t) for t in chunk["delta_token_ids"])
            lines.append(f"      delta_token_ids: [{ids}]")
        if chunk.get("finish_reason"):
            lines.append(f"      finish_reason: {chunk['finish_reason']}")

        rec = text_rec[ci] if ci < len(text_rec) else {"deltas": [], "normal_text": ""}
        dyn_deltas = rec.get("deltas", [])
        dyn_normal = rec.get("normal_text", "") or ""
        src_exp = chunk.get("expected", {}) or {}
        src_nt = chunk.get("normal_text", {}) or {}

        # expected: dynamo_v2 (text path) first, then peers verbatim from the token fixture.
        lines.append("      expected:")
        _emit_deltas(lines, "dynamo_v2", dyn_deltas)
        for impl in PEER_IMPLS:
            _emit_deltas(lines, impl, src_exp.get(impl, []))

        # normal_text: dynamo_v2 (text path) + peers verbatim, only when non-empty.
        nt_lines = []
        if dyn_normal:
            nt_lines.append(f"        dynamo_v2: {_q(dyn_normal)}")
        for impl in PEER_IMPLS:
            if src_nt.get(impl):
                nt_lines.append(f"        {impl}: {_q(src_nt[impl])}")
        if nt_lines:
            lines.append("      normal_text:")
            lines.extend(nt_lines)


def _emit_deltas(lines, impl, deltas):
    if deltas:
        lines.append(f"        {impl}:")
        for d in deltas:
            lines.append(f"        - {_delta_flow(d)}")
    else:
        lines.append(f"        {impl}: []")


def gen_file(token_file):
    doc = yaml.safe_load(open(token_file))
    text_rec = record_text_path(token_file)
    captured = doc.get("captured_with", {})

    lines = list(HEADER)
    lines.append("")
    lines.append("family: harmony_text")
    lines.append(f"model_label: {_q(MODEL_LABEL)}")
    lines.append("mode: streamv2")
    if captured:
        lines.append("captured_with:")
        for k, v in captured.items():
            lines.append(f"  {k}: {_q(v)}")
    lines.append("cases:")
    for cid, case in doc["cases"].items():
        emit_case(lines, cid, case, text_rec.get(cid, []))

    text = "\n".join(lines) + "\n"
    yaml.safe_load(text)  # validate
    out = os.path.join(TEXT_DIR, os.path.basename(token_file))
    open(out, "w").write(text)
    print(f"wrote {os.path.relpath(out, REPO_ROOT)} ({len(doc['cases'])} cases)", file=sys.stderr)


def main():
    token_files = sorted(
        os.path.join(TOKEN_DIR, f) for f in os.listdir(TOKEN_DIR) if f.endswith(".yaml")
    )
    # Remove stale hand-authored text fixtures so the dir mirrors the token corpus exactly.
    for f in os.listdir(TEXT_DIR):
        if f.endswith(".yaml"):
            os.remove(os.path.join(TEXT_DIR, f))
    for tf in token_files:
        gen_file(tf)


if __name__ == "__main__":
    main()
